FROM python:3.13-windowsservercore-1809

SHELL ["powershell", "-command"]

WORKDIR /app

COPY requirements-3.13/prefect.txt requirements/

RUN nslookup pypi.org
RUN ipconfig /all

RUN python -m pip install --no-cache-dir --upgrade wheel pip uv
RUN python -m uv pip install --no-cache-dir -r requirements/prefect.txt
