services:  
  queue:
    build:
      context: .
      dockerfile:  ./docker/queue/Dockerfile
    ports:
      - "4200:4200"
  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    environment:
      - PREFECT_API_URL=http://queue:4200/api
  producer:
    build:
      context: .
      dockerfile: ./docker/producer/Dockerfile
    environment:
      - PREFECT_API_URL=http://queue:4200/api
