name: Build runner image

on:
  push:
    branches:
      - main

jobs:
  build:
    concurrency: build-image-runner_serialized
    
    runs-on: ubuntu-24.04
    
    defaults:
      run:
        working-directory: create-openstack-image

    env:
      OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
      BUILD_KEYPAIR_PRIVATE_KEY: ${{ secrets.BUILD_KEYPAIR_PRIVATE_KEY }}

    steps:
      - uses: actions/checkout@v4

      - name: Make scripts executable
        run: |
          chmod +x ./scripts/os ./scripts/ssh ./scripts/scp ./scripts/swift

      - name: Create virtual environment
        run: |
          python3.12 -m venv venv-linux

      - name: Install dependencies
        run: |
          venv-linux/bin/python -m pip install --upgrade wheel pip uv
          venv-linux/bin/python -m uv pip install -r requirements-linux/build.txt

      - name: List OpenStack projects
        run: |
          ./scripts/os project list

      - name: Check if old `build-image-server` image exists
        id: image-exists
        run: |
          if ./scripts/os image show "build-image-server"; then
            echo "true" >> "$GITHUB_OUTPUT"
          else
            echo "false" >> "$GITHUB_OUTPUT"
          fi

      - if:  ${{ steps.image-exists.outputs.value }}
        name: Remove old `build-image-server` image
        run: |
          ./scripts/os image delete build-image-server

      - name: Create private key file
        run: |
          echo "$BUILD_KEYPAIR_PRIVATE_KEY" > config/build_keypair

      - name: Create key pair
        run: |
          ./scripts/os keypair create --public-key config/build_keypair.pub build_keypair

      - name: Spin up machine
        run: |
          ./scripts/os server create --image "Windows Server 2025 Datacenter SSH" --flavor "a8-ram16-disk50-perf1" \
            --key-name build_keypair --network ext-net1 build-image-server

      - name: Get IP address
        run: |
          set +e
          ip_address=""
          for i in $(seq 1 10)
          do
            ip_address=$(./scripts/os server show build-image-server -fjson -caddresses | jq -r '.addresses."ext-net1"|.[0]')
            if [ $? -eq 0 ] && [ "$ip_address" != "null" ]
            then
              break
            fi
            sleep 5
          done
          set -e
          
          if [ -z ip_address ] || [ "$ip_address" = "null" ]
          then
            false
          else
            export BUILD_IMAGE_SERVER_IP="$ip_address" 
            export SSH_LOCATION="Administrator@$ip_address"
          
            echo "IP address is $ip_address."
            echo "BUILD_IMAGE_SERVER_IP=$BUILD_IMAGE_SERVER_IP" >> "$GITHUB_ENV"
            echo "SSH_LOCATION=$SSH_LOCATION" >> "$GITHUB_ENV"
          fi

      - name: Get volume ID
        run: |
          BUILD_IMAGE_SERVER_VOLUME_ID=$( \
            ./scripts/os server show build-image-server --format=json --column=volumes_attached \
            | jq -r '.volumes_attached|.[0]|.id' \
          )
          echo "BUILD_IMAGE_SERVER_VOLUME_ID=$BUILD_IMAGE_SERVER_VOLUME_ID" >> "$GITHUB_ENV"

      - name: Set up ssh agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.BUILD_IMAGE_SERVER_PRIVATE_SSH_KEY }}

      - name: Wait till can connect via SSH
        run: |
          set +e
          success="false"
          for i in $(seq 1 10)
          do
            ssh -oStrictHostKeyChecking=no "$SSH_LOCATION" "echo Hello from \$env:ComputerName!" && success=true
            if [ "$success" = "true" ]
            then
              break
            fi
            sleep 5
          done
          set -e
          
          if [ "$success" = "false" ]
          then
            false
          else
            echo "Connected successfully."
          fi

      - name: Create `resultes` folder
        run: |
          ./scripts/ssh mkdir resultes

      - name: Download Python onto server
        run: |
          ./scripts/ssh \
            '$ProgressPreference="SilentlyContinue";' \
              Invoke-WebRequest \
                -Uri https://www.python.org/ftp/python/3.13.3/python-3.13.3-amd64.exe \
                -OutFile 'resultes\python-3.13.3-amd64.exe' \
            '; $ProgressPreference="Continue";'

      - name: Install Python on server
        run: |
          ssh "$SSH_LOCATION" 'Start-Process -Wait .\resultes\python-3.13.3-amd64.exe -ArgumentList /quiet'

      - name: Enable long paths on server
        run: |
          ./scripts/ssh New-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' \
            -Name LongPathsEnabled -Value 1 -PropertyType DWORD -Force

      - name: Show Python version
        run: |
          ssh "$SSH_LOCATION" 'py -3.13 -V'


      - name: Restart console so installation takes effect
        run: |
          if [ -f ~/.ssh/master-build_image_server ]; then
            ssh -o ControlPath=~/.ssh/master-build_image_server -O stop "$SSH_LOCATION"
            sleep 5
          fi

      - name: Copy `src` folder to server
        run: |
          ./scripts/scp -r ../requirements-3.13 ../src resultes

      - name: Create venv on server
        run: |
          ssh "$SSH_LOCATION" 'py -3.13 -m venv resultes\venv3.13'

      - name: Install requirements on server
        run: |
          ./scripts/ssh '.\resultes\venv3.13\Scripts\python -m pip install --upgrade wheel pip uv'
          ./scripts/ssh '.\resultes\venv3.13\Scripts\python -m uv pip install -r resultes\requirements-3.13\run-3rd-party.txt'

      - name: Install service on server
        run: |
          ./scripts/ssh New-Service -Name '"ResulTES runner"' -BinaryPathName \
            '"C:\Users\Administrator\resultes\venv3.13\Scripts\python.exe C:\Users\Administrator\resultes\src\main.py"' \
            -StartupType Automatic

      - name: Authenticate to swift
        run: |
          ./scripts/swift auth | awk '{print $2}' >> "$GITHUB_ENV"

      - name: Download TRNSYS onto server
        run: |
          ./scripts/ssh \
            '$ProgressPreference="SilentlyContinue";' \
              Invoke-WebRequest -Headers "@{\"X-Auth-Token\" = \"$OS_AUTH_TOKEN\"}" \
                -Uri "${OS_STORAGE_URL}/resultes/build-runner-image/TRNSYS18_resultes.zip?version-id=1745269323.13082" \
                -OutFile 'resultes\TRNSYS18_resultes.zip' \
            '; $ProgressPreference="Continue";'

      - name: Unzip TRNSYS to C:\ on server
        run: |
          ./scripts/ssh Expand-Archive -Path 'resultes\TRNSYS18_resultes.zip' -DestinationPath 'C:\\'

      - name: Shutdown server
        run: |
          ./scripts/ssh 'shutdown /s'

      - name: Build image from server
        run: |
          ./scripts/os server image create build-image-server
          
          status=""
          while [ -z "$status" || "$status" != "active" ]
          do
            status=$(./scripts/os image show build-image-server --format=value --column status)
            sleep 5
          done

      - name: Delete server
        run: |
          ./scripts/os server delete build-image-server
        if: ${{ always() }}

      - name: Delete key pair
        run: |
          ./scripts/os keypair delete build_keypair
        if: ${{ always() }}
