name: Build runner image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    concurrency: create-disk-image_serialized

    runs-on: windows-2025

    defaults:
      run:
        working-directory: create-disk-image

    steps:
      - name: Generate app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.READ_RESULTES_REPOS_APP_ID }}
          private-key: ${{ secrets.READ_RESULTES_REPOS_APP_KEY }}
          repositories: |
            runner
            pydantic-models
            openstack-utils
            jsonrpc

      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false
          submodules: "true"
          lfs: true

      - name: Create disk image file
        run: |
          New-Vhd -Path image.vhdx -SizeBytes 2GB

      - name: Mount disk image file
        run: |
          Mount-DiskImage -ImagePath $PWD\image.vhdx

      - name: Show disks
        run: |
          Get-Disk

      - name: Initialize disk
        run: |
          Initialize-Disk -Number 2

      - name: Create new partition
        run: |
          New-Partition -DiskNumber 2 -UseMaximumSize

      - name: Set drive letter
        run: |
          Set-Partition -DiskNumber 2 -PartitionNumber 2 -NewDriveLetter E

      - name: Format volume
        run: |
          Format-Volume -DriveLetter E

      - name: Copy start script
        run: |
          cp .\contents\start.ps1 E:\

      - name: Extract TRNSYS
        run: |
          Expand-Archive -Path .\contents\TRNSYS18_resultes.zip

      - name: Move TRNSYS to 'E:'
        run: |
          mv .\TRNSYS18_resultes\TRNSYS18 E:\

      - name: Unzip NSSM
        run: |
          Expand-Archive -Path .\contents\nssm-2.24.zip

      - name: Move NSSM folder to 'E:'
        run: |
          mv nssm-2.24 E:\

      - name: Create runner folder
        run: |
          mkdir E:\runner

      - name: Enable long paths
        run: |
          New-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name LongPathsEnabled -Value 1 -PropertyType DWORD -Force

      - name: Download stand-alone python
        run: |
          $ProgressPreference="SilentlyContinue"
          Invoke-WebRequest `
            https://github.com/astral-sh/python-build-standalone/releases/download/20251014/cpython-3.13.9+20251014-x86_64-pc-windows-msvc-install_only.tar.gz `
            -OutFile python.tar.gz
          $ProgressPreference="Continue"

      - name: Extract python
        run: |
          tar -xz -f python.tar.gz

      - name: Move python folder to 'E:\runner'
        run: |
          mv python E:\runner

      - name: Copy source files
        run: |
          cp -R ..\requirements-3.13 E:\runner
          cp -R ..\src E:\runner
          cp -R ..\pydantic-models E:\runner
          cp -R ..\openstack-utils E:\runner
          cp -R ..\jsonrpc E:\runner
          cp -R ..\config E:\runner

      - name: Add OS auth secret
        run: |
          mkdir -Force E:\runner\config\secrets
          $env:SWIFT_OPERATOR_APPLICATION_CREDENTIAL_YAML | ` 
              Out-File -FilePath E:\runner\config\secrets\swift-operator-application-credential.yaml -NoNewline

      - name: List contents of 'E:\runner'
        run: |
          ls E:\runner\

      - name: Install requirements
        working-directory: E:\runner\
        run: |
          .\python\python.exe -m pip install --upgrade wheel pip uv
          .\python\python.exe -m uv pip install -r .\requirements-3.13\run.txt

      - name: Unmount disk image file
        run: |
          Dismount-DiskImage -ImagePath $PWD\image.vhdx

      - name: Create venv
        run: |
          py -3.12 -m venv venv
          .\venv\Scripts\python.exe -m pip install --upgrade wheel pip uv
          .\venv\Scripts\python.exe -m uv pip sync .\requirements\build.txt

      - name: Upload image
        run: |
          .\scripts\os.ps1 image create --file image.vhdx --disk-format vhdx runner-disk-image
