name: Create and publish Docker images

on:
  push:
    branches:
      - main

jobs:
  build-and-push-base-docker-image:
    runs-on: windows-2019
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        # See https://stackoverflow.com/questions/47074457/how-to-specify-docker-build-network-host-mode-in-docker-compose-at-the-time
        # for details on --network=host
        run: |
          docker build -f Dockerfile-prefect -t spf-ost/resultes-runner-prefect:latest --network=host .
          docker push spf-ost/resultes-runner-prefect:latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/spf-ost/resultes-runner-prefect:latest
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
            
  build-and-push-images:
    runs-on: windows-2019
    needs: build-and-push-base-docker-image
    strategy:
      matrix:
        include:
          - dockerfile: ./docker/producer/Dockerfile
            name: resultes-runner-producer
          - dockerfile: ./docker/queue/Dockerfile
            image: resultes-runner-queue
          - dockerfile: ./docker/worker/Dockerfile
            image: resultes-runner-worker
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        # See https://stackoverflow.com/questions/47074457/how-to-specify-docker-build-network-host-mode-in-docker-compose-at-the-time
        # for details on --network=host
        run: |
          docker build -f $ {{ matrix.dockerfile }} -t spf-ost/${{ matrix.name }}:latest --network=host .
          docker push spf-ost/${{ matrix.name }}:latest

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/spf-ost/${{ matrix.name }}:latest
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
      
