name: Create and publish Docker images

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push-base-docker-image:
    concurrency: build-and-push-base-docker-image_serialized

    runs-on: windows-2019
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f Dockerfile-prefect -t ghcr.io/resultes-net/resultes-runner-prefect:latest .

      - name: Push Docker image
        id: push
        run: |
          $image_digest=$(py -3.12 push_docker_image_and_get_digest.py ghcr.io/resultes-net/resultes-runner-prefect:latest)
          echo "image_digest=${image_digest}" >> $env:GITHUB_OUTPUT
  
  build-and-push-images:
    concurrency: build-and-push-images_serialized

    runs-on: windows-2019
    needs: build-and-push-base-docker-image
    strategy:
      matrix:
        include:
          - dockerfile: ./docker/producer/Dockerfile
            name: resultes-runner-producer
          - dockerfile: ./docker/queue/Dockerfile
            name: resultes-runner-queue
          - dockerfile: ./docker/worker/Dockerfile
            name: resultes-runner-worker
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -f ${{ matrix.dockerfile }} -t ghcr.io/resultes-net/${{ matrix.name }}:latest .

      - name: Push Docker image
        id: push
        run: |
          $image_digest=$(py -3.12 push_docker_image_and_get_digest.py ghcr.io/resultes-net/${{ matrix.name }}:latest)
          echo "image_digest=${image_digest}" >> $env:GITHUB_OUTPUT
